version: "3"

services:
  backend-commits:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: api-commits
    enviroment:
      PORT: "3001"
      GIT_HUB_KEY: "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"
    ports:
      - "3001:3001"
  frontend-commits:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: react-commits-app
    ports:
      - "3000:3000"
    depends_on:
      - "backend-commits"
