version: "3"

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
      image: api-commits
      enviroment:
        PORT: "3001"
        GIT_HUB_KEY: "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"
    ports:
      - "3001:3001"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: react-commits-app
    ports:
      - "3000:3000"
    links:
      - "backend:api"
